affilliate_link_map:
  default: "digitalocean.com,https://m.do.co/c/a5bf212d9a92"
  type: "list"
  description: "Deprecated. Use affiliate_link_map instead."
affiliate_link_map:
  default: "example.com,https://example.com/affilliate/1234"
  type: "list"
  description: "hostname,referal link"
